### ISSUE TITLE
关于使用的一个疑问

### ISSUE THREAD

**Issue by luoaolalala** [Ko-oK-OS/xv6-rust#25]
显示到first user process init.....后就直接shutdown了，是因为在rust_main.rs里面注释掉的代码吗

**Comment by KuangjuX** [comment]
你好，感谢你对项目的使用和提出反馈。
是这样的，我们的项目的文件系统仍在开发中，因此目前仍然不是一个完整的内核，无法去运行用户程序。因此我们目前是在操作系统启动进行一系列初始化后实行关机。
如果你想去一直运行，可以注释掉`panic`，改成`loop`，操作系统将会持续运行。

**Comment by KuangjuX** [comment]
我关闭这个issue了，如果你有问题，仍然可以重新开启这个issue。
