### ISSUE TITLE
关于内存分配

### ISSUE THREAD

**Issue by Shuimo03** [Ko-oK-OS/xv6-rust#43]
你好，想请问下如何看到内存情况？

**Comment by KuangjuX** [comment]
目前我们使用自己开发的伙伴内存分配系统来做内存分配，可以在 alloc 和 dealloc 的时候打印一下分配的 layout 信息，如果需要实时查看的话或许就要在内存分配中加一些支持了

**Comment by Shuimo03** [comment]
谢谢老哥，因为我毕设是操作系统内存相关的，所以比较好奇，再次感谢！

**Comment by KuangjuX** [comment]
不用客气，有问题可以随时交流，这个也是我第一次写操作系统，很多设计还不好，之后可能会大幅度重构或者重写。
