### ISSUE TITLE
switch.S

### ISSUE THREAD

**Issue by Shuimo03** [Ko-oK-OS/xv6-rust#44]
`global_asm!(include_str!("asm/entry.S"));
global_asm!(include_str!("asm/kernelvec.S"));
global_asm!(include_str!("asm/trampoline.S"));
global_asm!(include_str!("asm/switch.S"));
`
master分支下没有switch.S文件

**Comment by KuangjuX** [comment]
这个文件不知道为啥被 ignore 了..... 已经加上了

**Comment by Shuimo03** [comment]
谢谢了

**Comment by Shuimo03** [comment]
可以加个好友嘛？

**Comment by KuangjuX** [comment]
可以啊

**Comment by Shuimo03** [comment]
我加你微信吧😄

**Comment by KuangjuX** [comment]
给你发邮件了
