### ISSUE TITLE
Cannot build xv6-rust: failed to get `allocator` as a dependency of package

### ISSUE THREAD

**Issue by anta40** [Ko-oK-OS/xv6-rust#46]
I'm on MacOS Big Sur with the latest nightly Rust installed:

> $ rustc --version
> rustc 1.60.0-nightly (bfe156467 2022-01-22) 

I also already had another tools installed:

> $ rustup target add riscv64gc-unknown-none-elf
> $ cargo install cargo-binutils
> $ rustup component add llvm-tools-preview

Now let's run **make**:
> $ cd xv6-rust/kernel
> make 
> ...
> ...
> error: failed to get `allocator` as a dependency of package `kernel v0.1.0 (/Users/andre/Lab/OSDev/xv6-rust/kernel)`
>
>Caused by:
> failed to load source for dependency `allocator`
>
> Caused by:
>  Unable to update /Users/andre/Lab/OSDev/xv6-rust/allocator
>
> Caused by:
>  failed to read `/Users/andre/Lab/OSDev/xv6-rust/allocator/Cargo.toml`
>
> Caused by:
>  No such file or directory (os error 2)
> make: *** [kernel] Error 101

**Comment by KuangjuX** [comment]
I'm guessing it's because the allocator's code isn't pulled down. Try to execute `git submodule update --init --recursive` to get the source code of the allocator crate.

**Comment by KuangjuX** [comment]
I have updated README.
