### ISSUE TITLE
xv6 riscv本身是一个完整的操作系统吗？还是说得做完xv6的实验 xv6 riscv才是完整的系统啊？

### ISSUE THREAD

**Issue by lsy1109** [Ko-oK-OS/xv6-rust#47]
请问xv6 riscv本身是一个完整的操作系统吗？还是说得做完xv6的实验 xv6 riscv才是完整的系统啊？

**Comment by KuangjuX** [comment]
xv6-riscv 本身就是完整的内核，MIT 6.S081 是在 xv6-riscv 的基础上添加功能
